### ISSUE TITLE
Forked opener-docker-wrapper

### ISSUE THREAD

**Issue by ghost** [c-w/opener-docker-wrapper#1]
Just dropping you a message, I have forked your wrapper repo and have added more pipelines. I followed your pattern, just want to make sure you get credit for your hard work. I will be adding more pipelines when I get the chance.

Thanks for your help.

https://github.com/devkws/opener-docker-wrapper 
https://hub.docker.com/r/devkws/opener-docker-wrapper/

https://github.com/devkws/opener-docker-constituent-parser
https://hub.docker.com/r/devkws/opener-docker-constituent-parser/

https://github.com/devkws/opener-docker-polarity-tagger
https://hub.docker.com/r/devkws/opener-docker-polarity-tagger/

https://github.com/devkws/opener-docker-opinion-detector-basic
https://hub.docker.com/r/devkws/opener-docker-opinion-detector-basic/

**Comment by c-w** [comment]
This is excellent, thanks! I've added links to your fork and additional NLP services to the project's README to make them easily discoverable to people who find this repository via my article.
